export const GAME_CONFIG = {
  INITIAL_BALANCE: 1000,
  BET_AMOUNT: 10,
  REELS_COUNT: 5,
  ROWS_COUNT: 3,
  MAX_ENTITIES: 500,

  GAME_WIDTH: 1280,
  GAME_HEIGHT: 720,

  FRAME_X: 267,
  FRAME_Y: 134,
  FRAME_W: 747,
  FRAME_H: 452,
  FRAME_PADDING: 15,

  SYMBOL_SIZE: 130,
  SYMBOL_GAP: 10,
  REEL_WIDTH: 143,

  REEL_STOP_BASE_DELAY: 1000,
  REEL_STOP_INCREMENT: 400,
  SPIN_SPEED: 1.6,
  TURBO_MULTIPLIER: 2.5,
  BOUNCE_DURATION: 200,
  BOUNCE_DISTANCE: 15,
  WIN_DISPLAY_DURATION: 2000,

  TALL_BAR_CHANCE: 0.3,
  TALL_SYMBOL_ROWS: 2,

  AUTO_PLAY_OPTIONS: [10, 25, 50, 100] as const,

  BG_COLOR: 0x040e2e,
  FALLBACK_BG_COLOR: 0x0a0a2e,
  LOGO_Y: 5,
  LOGO_SCALE: 0.4,
  SYMBOL_BORDER_RADIUS: 8,
  SPRITES_PER_REEL: 4,

  WIN_PULSE_AMPLITUDE: 0.08,
  WIN_PULSE_SPEED: 0.005,
  WIN_LINE_WIDTH: 4,
  WIN_LINE_ALPHA: 0.9,

  PORTRAIT_PADDING: 12,
  PORTRAIT_TOP_OFFSET_RATIO: 0.3,

  SOUND_VOLUME_SPIN: 0.5,
  SOUND_VOLUME_REEL: 0.6,
  SOUND_VOLUME_WIN: 0.7,
  SOUND_VOLUME_BG: 0.3,
  SOUND_VOLUME_CLICK: 0.5,
  SOUND_POOL_MAX: 4,

  KEY_REPEAT_INTERVAL: 200,

  REEL_STOP_QUEUE_PADDING: 3,

  MASCOT_Y_OFFSET: 100,
  MASCOT_HEIGHT_RATIO: 0.4,
  MASCOT_FALLBACK_HEIGHT: 385,
  MASCOT_TIME_SCALE: 0.5,
};

export const CELL_HEIGHT = GAME_CONFIG.SYMBOL_SIZE + GAME_CONFIG.SYMBOL_GAP;
export const REELS_LEFT = GAME_CONFIG.FRAME_X + GAME_CONFIG.FRAME_PADDING;
export const REELS_TOP = GAME_CONFIG.FRAME_Y + GAME_CONFIG.FRAME_PADDING;
