export const GAME_CONFIG = {
  INITIAL_BALANCE: 1000,
  BET_AMOUNT: 10,
  REELS_COUNT: 5,
  ROWS_COUNT: 3,
  MAX_ENTITIES: 500,

  GAME_WIDTH: 1280,
  GAME_HEIGHT: 720,

  FRAME_X: 267,
  FRAME_Y: 134,
  FRAME_W: 747,
  FRAME_H: 452,
  FRAME_PADDING: 15,

  SYMBOL_SIZE: 130,
  SYMBOL_GAP: 10,
  REEL_WIDTH: 143,

  REEL_STOP_BASE_DELAY: 1000,
  REEL_STOP_INCREMENT: 400,
  SPIN_SPEED: 1.6,
  TURBO_MULTIPLIER: 2.5,
  BOUNCE_DURATION: 200,
  BOUNCE_DISTANCE: 15,
  WIN_DISPLAY_DURATION: 2000,

  TALL_BAR_CHANCE: 0.3,

  AUTO_PLAY_OPTIONS: [10, 25, 50, 100] as const,
};

export const CELL_HEIGHT = GAME_CONFIG.SYMBOL_SIZE + GAME_CONFIG.SYMBOL_GAP;
export const REELS_LEFT = GAME_CONFIG.FRAME_X + GAME_CONFIG.FRAME_PADDING;
export const REELS_TOP = GAME_CONFIG.FRAME_Y + GAME_CONFIG.FRAME_PADDING;
